networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: docker.io/bitnami/mongodb:8.0.4
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=P1zz4M45ter
      - MONGODB_USERNAME=pizza
      - MONGODB_PASSWORD=pizza
    networks:
      - app-tier

volumes:
  mongodb_data:
    driver: local

