server:
  port: 8383
spring:
  application:
    name: modular-pizza-hut
  datasource:
    url: jdbc:h2:mem:pizzeria;NON_KEYWORDS=user
    generate-unique-name: false
    name: pizzeria
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: pizza
#      password: pizza
#      database: pizza
#      uuid-representation: standard